name: robot_ci

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://wpilib/roborio-cross-ubuntu:2023-22.04
      - run: |
          echo "Hello World"